In [27]:
import pandas as pd
import os
import glob
from tqdm.notebook import tqdm
tqdm.pandas()

Header proposé dans le papier :
| Nom dans notre dataset | Abréviations | Description |
| ---------------------- | ------------ | ----------- |
| `datetime_end` | `te` | Date and time of the end of a flow |
| `duration` | `td` | Duration of the flow  |
| `source_ip` | `sa` | Source IP Address |
| `destination_ip` | `da` | Destination IP Address |
| `source_port` | `sp` | Source Port |
| `destination_port` | `dp` | Destination Port |
| `protocol` | `pr` | Protocol |
| `flag` | `flg` | Flag |
| `forwarding` | `fwd` | Forwarding status  |
| `type` | `stos` | Type of Service (ToS) byte |
| `packet` | `pkt` | Packets exchanged |
| `byte` | `byt` | Bytes exchanged |
| `label` | `lb` | Label |

In [28]:
EXTRACT_PATH = "../data/extract/"
SAMPLES_PATH = os.path.join(EXTRACT_PATH, "samples")
HEADER = ["datetime_end", "duration", "source_ip", "destination_ip", "source_port", "destination_port", "protocol", "flag", "forwarding", "type",
          "packet", "byte", "label"]
LABEL_LIST = ["background", "blacklist", "anomaly-spam", "anomaly-sshscan", "anomaly-udpscan", "dos", "scan11", "scan44", "nerisbotnet"]

## Concat samples

In [29]:
samples_path_list = glob.glob(os.path.join(SAMPLES_PATH, "*.csv"))
samples_path_list

['../data/extract/samples/calibration-april.week5.csv',
 '../data/extract/samples/calibration-may.week4.csv',
 '../data/extract/samples/calibration-june.week4.csv',
 '../data/extract/samples/calibration-april.week2.csv',
 '../data/extract/samples/test-august.week5.csv',
 '../data/extract/samples/calibration-june.week2.csv',
 '../data/extract/samples/calibration-may.week2.csv',
 '../data/extract/samples/calibration-may.week6.csv',
 '../data/extract/samples/test-august.week1.csv',
 '../data/extract/samples/test-august.week2.csv',
 '../data/extract/samples/calibration-march.week5.csv',
 '../data/extract/samples/calibration-june.week3.csv',
 '../data/extract/samples/calibration-may.week5.csv',
 '../data/extract/samples/calibration-march.week4.csv',
 '../data/extract/samples/test-august.week3.csv',
 '../data/extract/samples/calibration-april.week4.csv',
 '../data/extract/samples/calibration-april.week3.csv',
 '../data/extract/samples/calibration-june.week1.csv',
 '../data/extract/samples/calibration-may.week3.csv',
 '../data/extract/samples/test-august.week4.csv',
 '../data/extract/samples/test-july.week5.csv',
 '../data/extract/samples/calibration-march.week3.csv',
 '../data/extract/samples/calibration-may.week1.csv']

In [14]:
dataset_df = pd.read_csv(samples_path_list[0], names=HEADER)
for samples_path in tqdm(samples_path_list[1:]):
    sample_df = pd.read_csv(samples_path, names=HEADER)
    dataset_df = pd.concat([dataset_df, sample_df])

100%|██████████| 22/22 [00:34<00:00,  1.57s/it]

In [15]:
dataset_df

,datetime_end,duration,source_ip,destination_ip,source_port,destination_port,protocol,flag,forwarding,type,packet,byte,label
0,2016-04-25 00:02:06,0.512,42.219.155.56,223.87.133.32,80,63163,TCP,.AP.SF,0,0,15,17358,background
1,2016-04-25 00:02:06,4.484,211.42.204.231,42.219.156.211,59045,80,TCP,.AP.S.,0,0,5,656,background
2,2016-04-25 00:02:08,6.040,42.219.156.211,211.33.253.2,443,41417,TCP,.AP.SF,0,0,11,5914,background
3,2016-04-25 00:02:09,2.988,42.219.159.95,232.199.145.70,42393,445,TCP,....S.,0,0,2,96,background
4,2016-04-25 00:02:20,0.024,42.219.155.105,36.50.44.138,22,53952,TCP,.AP.SF,0,0,4,237,background
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57665,2016-05-02 00:03:11,1.804,42.219.153.128,106.150.228.108,80,15091,TCP,.A..SF,0,0,3,128,background
57666,2016-05-02 00:03:13,0.316,42.219.159.85,53.169.167.74,52461,80,TCP,.AP.SF,0,0,9,612,blacklist
57667,2016-05-02 00:03:16,0.452,42.219.156.211,212.115.231.155,443,50958,TCP,.AP.SF,0,0,8,2041,background
57668,2016-05-02 00:03:20,0.528,42.219.159.85,53.169.167.74,52483,80,TCP,.AP.SF,0,0,9,612,blacklist
57669,2016-05-02 00:03:22,4.220,42.219.156.211,219.196.235.107,443,64462,TCP,.AP.SF,0,0,8,2168,background

In [16]:
dataset_df["label"].value_counts()

background         7200000
blacklist           900000
anomaly-spam        900000
anomaly-sshscan     900000
anomaly-udpscan     900000
dos                 900000
scan11              900000
scan44              900000
nerisbotnet         900000
Name: label, dtype: int64

In [17]:
900_000*8

7200000

In [19]:
DATASET_LARGE_NAME = "ugr16-large.csv"
export_path = os.path.join(EXTRACT_PATH, DATASET_LARGE_NAME)
dataset_df.to_csv(export_path)

## Reduce dataset

### Base

In [3]:
dataset_df = pd.read_csv(os.path.join(EXTRACT_PATH, "ugr16-large.csv"), index_col=0)

In [4]:
dataset_df

,datetime_end,duration,source_ip,destination_ip,source_port,destination_port,protocol,flag,forwarding,type,packet,byte,label
0,2016-04-25 00:02:06,0.512,42.219.155.56,223.87.133.32,80,63163,TCP,.AP.SF,0,0,15,17358,background
1,2016-04-25 00:02:06,4.484,211.42.204.231,42.219.156.211,59045,80,TCP,.AP.S.,0,0,5,656,background
2,2016-04-25 00:02:08,6.040,42.219.156.211,211.33.253.2,443,41417,TCP,.AP.SF,0,0,11,5914,background
3,2016-04-25 00:02:09,2.988,42.219.159.95,232.199.145.70,42393,445,TCP,....S.,0,0,2,96,background
4,2016-04-25 00:02:20,0.024,42.219.155.105,36.50.44.138,22,53952,TCP,.AP.SF,0,0,4,237,background
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57665,2016-05-02 00:03:11,1.804,42.219.153.128,106.150.228.108,80,15091,TCP,.A..SF,0,0,3,128,background
57666,2016-05-02 00:03:13,0.316,42.219.159.85,53.169.167.74,52461,80,TCP,.AP.SF,0,0,9,612,blacklist
57667,2016-05-02 00:03:16,0.452,42.219.156.211,212.115.231.155,443,50958,TCP,.AP.SF,0,0,8,2041,background
57668,2016-05-02 00:03:20,0.528,42.219.159.85,53.169.167.74,52483,80,TCP,.AP.SF,0,0,9,612,blacklist
57669,2016-05-02 00:03:22,4.220,42.219.156.211,219.196.235.107,443,64462,TCP,.AP.SF,0,0,8,2168,background

In [5]:
dataset_df["label"].value_counts()

background         7200000
blacklist           900000
anomaly-spam        900000
anomaly-sshscan     900000
anomaly-udpscan     900000
dos                 900000
scan11              900000
scan44              900000
nerisbotnet         900000
Name: label, dtype: int64

In [12]:
def sample_label(df, sample_size=90_000):
    if (df.label == "background").all():
        return df.sample(n=sample_size*8)
    return df.sample(n=sample_size)

In [13]:
reduced_dataset_df = dataset_df.groupby("label").progress_apply(sample_label).reset_index(drop=True)

  0%|          | 0/9 [00:00<?, ?it/s]

In [14]:
reduced_dataset_df

,datetime_end,duration,source_ip,destination_ip,source_port,destination_port,protocol,flag,forwarding,type,packet,byte,label
0,2016-08-07 04:48:34,0.616,42.219.156.212,253.139.127.227,54594,25,TCP,.APRS.,0,0,6,433,anomaly-spam
1,2016-08-08 23:39:59,0.584,177.235.191.18,42.219.156.223,25,33008,TCP,.AP.SF,0,0,5,564,anomaly-spam
2,2016-08-08 19:20:10,0.572,42.219.156.213,194.192.119.230,38880,25,TCP,.APRS.,0,0,6,443,anomaly-spam
3,2016-08-07 00:11:24,0.616,42.219.156.223,253.139.127.227,55611,25,TCP,.APRS.,0,0,6,441,anomaly-spam
4,2016-08-09 04:48:51,0.720,42.219.156.223,253.136.161.201,40400,25,TCP,.APRS.,0,0,6,442,anomaly-spam
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439995,2016-08-03 12:50:42,0.000,42.219.150.246,42.219.158.16,46660,22939,TCP,....S.,0,0,1,44,scan44
1439996,2016-08-07 20:51:26,0.000,42.219.156.30,42.219.150.247,6009,63808,TCP,.A.R..,0,0,1,40,scan44
1439997,2016-08-04 00:13:08,0.000,42.219.156.30,42.219.150.247,8888,42314,TCP,.A.R..,0,0,1,40,scan44
1439998,2016-07-28 12:31:35,0.000,42.219.156.30,42.219.150.247,52673,42464,TCP,.A.R..,0,0,1,40,scan44
1439999,2016-07-30 04:51:01,0.000,42.219.150.242,42.219.154.69,57820,5100,TCP,....S.,0,0,1,44,scan44

In [15]:
reduced_dataset_df["label"].value_counts()

background         720000
anomaly-spam        90000
anomaly-sshscan     90000
anomaly-udpscan     90000
blacklist           90000
dos                 90000
nerisbotnet         90000
scan11              90000
scan44              90000
Name: label, dtype: int64

In [18]:
DATASET_BASE_NAME = "ugr16-base.csv"
export_path = os.path.join(EXTRACT_PATH, DATASET_BASE_NAME)
reduced_dataset_df.to_csv(export_path)

### Small

In [19]:
dataset_df = pd.read_csv(os.path.join(EXTRACT_PATH, "ugr16-large.csv"), index_col=0)

In [20]:
dataset_df

,datetime_end,duration,source_ip,destination_ip,source_port,destination_port,protocol,flag,forwarding,type,packet,byte,label
0,2016-04-25 00:02:06,0.512,42.219.155.56,223.87.133.32,80,63163,TCP,.AP.SF,0,0,15,17358,background
1,2016-04-25 00:02:06,4.484,211.42.204.231,42.219.156.211,59045,80,TCP,.AP.S.,0,0,5,656,background
2,2016-04-25 00:02:08,6.040,42.219.156.211,211.33.253.2,443,41417,TCP,.AP.SF,0,0,11,5914,background
3,2016-04-25 00:02:09,2.988,42.219.159.95,232.199.145.70,42393,445,TCP,....S.,0,0,2,96,background
4,2016-04-25 00:02:20,0.024,42.219.155.105,36.50.44.138,22,53952,TCP,.AP.SF,0,0,4,237,background
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57665,2016-05-02 00:03:11,1.804,42.219.153.128,106.150.228.108,80,15091,TCP,.A..SF,0,0,3,128,background
57666,2016-05-02 00:03:13,0.316,42.219.159.85,53.169.167.74,52461,80,TCP,.AP.SF,0,0,9,612,blacklist
57667,2016-05-02 00:03:16,0.452,42.219.156.211,212.115.231.155,443,50958,TCP,.AP.SF,0,0,8,2041,background
57668,2016-05-02 00:03:20,0.528,42.219.159.85,53.169.167.74,52483,80,TCP,.AP.SF,0,0,9,612,blacklist
57669,2016-05-02 00:03:22,4.220,42.219.156.211,219.196.235.107,443,64462,TCP,.AP.SF,0,0,8,2168,background

In [21]:
dataset_df["label"].value_counts()

background         7200000
blacklist           900000
anomaly-spam        900000
anomaly-sshscan     900000
anomaly-udpscan     900000
dos                 900000
scan11              900000
scan44              900000
nerisbotnet         900000
Name: label, dtype: int64

In [22]:
def sample_label(df, sample_size=9_000):
    if (df.label == "background").all():
        return df.sample(n=sample_size*8)
    return df.sample(n=sample_size)

In [23]:
reduced_dataset_df = dataset_df.groupby("label").progress_apply(sample_label).reset_index(drop=True)

  0%|          | 0/9 [00:00<?, ?it/s]

In [24]:
reduced_dataset_df

,datetime_end,duration,source_ip,destination_ip,source_port,destination_port,protocol,flag,forwarding,type,packet,byte,label
0,2016-08-07 21:08:25,0.484,253.139.127.229,42.219.156.215,25,48324,TCP,.AP.SF,0,0,5,564,anomaly-spam
1,2016-08-08 14:10:17,0.468,253.139.127.230,42.219.156.213,25,51871,TCP,.AP.SF,0,0,5,564,anomaly-spam
2,2016-03-24 11:35:33,0.296,42.219.156.223,108.66.255.194,40484,25,TCP,.A.RS.,0,0,4,216,anomaly-spam
3,2016-08-07 00:10:32,2.616,42.219.156.214,194.192.119.38,44877,25,TCP,.APRS.,0,0,21,7486,anomaly-spam
4,2016-08-06 22:40:05,0.364,194.192.119.34,42.219.156.215,25,35728,TCP,.AP.SF,0,0,5,564,anomaly-spam
...,...,...,...,...,...,...,...,...,...,...,...,...,...
143995,2016-08-07 06:41:17,0.000,42.219.156.30,42.219.150.247,9220,53933,TCP,.A.R..,0,0,1,40,scan44
143996,2016-08-01 20:56:52,0.012,42.219.150.246,42.219.158.16,49487,15660,TCP,...RS.,0,0,2,84,scan44
143997,2016-08-05 16:50:09,0.000,42.219.150.242,42.219.154.69,58926,32774,TCP,....S.,0,0,1,44,scan44
143998,2016-08-09 11:20:16,0.000,42.219.150.247,42.219.156.30,42844,5815,TCP,....S.,0,0,1,44,scan44
143999,2016-07-29 15:41:11,0.000,42.219.156.30,42.219.150.247,3869,38363,TCP,.A.R..,0,0,1,40,scan44

In [26]:
reduced_dataset_df["label"].value_counts()

background         72000
anomaly-spam        9000
anomaly-sshscan     9000
anomaly-udpscan     9000
blacklist           9000
dos                 9000
nerisbotnet         9000
scan11              9000
scan44              9000
Name: label, dtype: int64

In [25]:
DATASET_BASE_NAME = "ugr16-small.csv"
export_path = os.path.join(EXTRACT_PATH, DATASET_BASE_NAME)
reduced_dataset_df.to_csv(export_path)